name: sync develop with main
# creates both a branch and a PR to sync changes from main back to the develop branches
on:
  push:
    branches:
    - main
jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        branch:
        - test-1
        - test-2
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        # fetch the 100 most recent commits
        fetch-depth: 100
    - name: Create PR from main to develop/${{ matrix.branch }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: main
        destination: develop/${{ matrix.branch }}
        title: "chore: integrate main to develop/${{ matrix.branch }}"
        body: "Automated PR to sync main into develop/${{ matrix.branch }}"
        branch: feature/${{ matrix.branch }}/integrate-main
        labels: automerge
        draft: false
        delete-branch: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
